def raise_exception():
    try:
        raise Exception